### ISSUE TITLE
DK_STAT_SYNTAX error on domain keys signing

### ISSUE THREAD

**Issue by toptensoftware** [dmcgiv/DKIM.Net#1]
Hi,

I'm trying to use DKIM.NET to sign email messages being sent through gmail and getting the following error back from check-auth@verifier.port25.com on the domain key signature:

```
----------------------------------------------------------
DomainKeys check details:
----------------------------------------------------------
Result:         permerror (DK_STAT_SYNTAX: Message is not valid syntax. Signature could not be created/checked)
ID(s) verified: header.=
DNS record(s):
```

The generated header is:

```
DomainKey-Signature: a=rsa-sha256; c=simple; d=showcaselane.com; h=From:To:Subject; q=dns;
 s=selector;
 b=UjIbMn/14hGIJn/BzRYuIPqjueRm47jh16FNAfY3ZFQ3LugTXFe/Vc8knQFuNtqV9yMpc1OGBsyK8jAHJ/4C55oyeixzUkcmZwAtenpml30PJG421dm3jb8maivJFkW9i/qFQ9MiDzWazhIlAJN1rDhCV/0blkFyhizTExNS/Bs=;
```

Signing with DKIM (as opposed to DomainKeys) works fine.

**Comment by toptensoftware** [comment]
found the issue... wasn't passing hashing algorithm sha1 to the private key constructor, causing it to use sha256 for domainkey signing - which isn't allowed.

**Comment by dmcgiv** [comment]
Hi,

 I came across this issue also and have a fixed version but which also
breaks the current API. I'll try and get it completed and committed soon.

Damien
